version: '3'
services:

  rabbit:
    image: rabbitmq:3.8-management
    restart: unless-stopped
    ports:
      - "5671-5672:5671-5672"
      - "15672:15672"
      - "4369:4369"
      - "15671:15671"

  mongo:
    image: mongo:4
    restart: unless-stopped
    ports:
      - "27017:27017"

  sure-tosca:
    image: qcdis/sure-tosca:1.0.2
    restart: unless-stopped
    ports:
      - "8081:8081"


  planner:
    depends_on:
      - rabbit
      - sure-tosca
    image: qcdis/sdia-infrastructure-planner:1.0.4
    restart: unless-stopped
    environment:
      RABBITMQ_HOST: rabbit
