version: '3'
services:
    
  rabbit:
    image: rabbitmq:3.8-management
    ports:   
      - "5671-5672:5671-5672"
      - "15672:15672"
      - "4369:4369"
      - "15671:15671"     

 
      
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"               
   
            
  sure-tosca:
    image: qcdis/sure-tosca
    ports: 
      - "8081:8081"
   
